"""utc time zone and flight stuff

Revision ID: 24233e79b8f1
Revises: 85913aa121cc
Create Date: 2023-09-28 16:14:38.626663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24233e79b8f1'
down_revision = '85913aa121cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utc_offset', sa.Integer(), nullable=True))

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('timezone_change', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('departure', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('arrival', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('arrival')
        batch_op.drop_column('departure')
        batch_op.drop_column('timezone_change')
        batch_op.drop_column('distance')

    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_column('utc_offset')

    # ### end Alembic commands ###
