"""revert to interval for timezone and flight time

Revision ID: 248ce76d0dfb
Revises: e6726f4022fa
Create Date: 2023-10-24 17:54:30.583390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248ce76d0dfb'
down_revision = 'e6726f4022fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('timezone_change',
               existing_type=sa.INTEGER(),
               type_=sa.Interval(),
               existing_nullable=True)
        batch_op.alter_column('flight_time',
               existing_type=sa.INTEGER(),
               type_=sa.Interval(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('flight_time',
               existing_type=sa.Interval(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('timezone_change',
               existing_type=sa.Interval(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
