"""add coordinates to airports, change property names

Revision ID: 353e7f444f2a
Revises: f9ddb3d1a9e2
Create Date: 2023-09-05 15:27:18.627515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353e7f444f2a'
down_revision = 'f9ddb3d1a9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_column('coords_latitude')
        batch_op.drop_column('coords_longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coords_longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('coords_latitude', sa.FLOAT(), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
