"""revert tz change to integer

Revision ID: 509bb588b5a9
Revises: b6cc78093b98
Create Date: 2023-10-24 20:12:14.208828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509bb588b5a9'
down_revision = 'b6cc78093b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('timezone_change',
               existing_type=sa.TIME(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('departure',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('arrival',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.alter_column('arrival',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('departure',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('timezone_change',
               existing_type=sa.Integer(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
