"""add level

Revision ID: 85913aa121cc
Revises: 353e7f444f2a
Create Date: 2023-09-27 12:39:15.596981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85913aa121cc'
down_revision = '353e7f444f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
