"""remove flight departure/arrival

Revision ID: a823157341fb
Revises: 24233e79b8f1
Create Date: 2023-09-28 17:10:26.101602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a823157341fb'
down_revision = '24233e79b8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('departure')
        batch_op.drop_column('arrival')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('departure', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
