"""create airports

Revision ID: e534b7e5d6a6
Revises: ff6f703e91ef
Create Date: 2023-08-24 18:06:33.550475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e534b7e5d6a6'
down_revision = 'ff6f703e91ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('id_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_reservations_conf_number'), ['conf_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_reservations_conf_number'), type_='unique')

    op.drop_table('airports')
    # ### end Alembic commands ###
