"""flight time, departure, arrival

Revision ID: e56e6e323a2e
Revises: a823157341fb
Create Date: 2023-10-11 18:22:37.900358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56e6e323a2e'
down_revision = 'a823157341fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('departure', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('arrival', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('arrival')
        batch_op.drop_column('departure')
        batch_op.drop_column('flight_time')

    # ### end Alembic commands ###
