"""add coordinates to airports

Revision ID: f9ddb3d1a9e2
Revises: 0b550f880ec9
Create Date: 2023-09-05 15:23:37.481888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ddb3d1a9e2'
down_revision = '0b550f880ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coords_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('coords_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airports', schema=None) as batch_op:
        batch_op.drop_column('coords_longitude')
        batch_op.drop_column('coords_latitude')

    # ### end Alembic commands ###
